apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webhook
resources:
  - ../../base
  - secret-avp.yaml
transformers:
- transformer-labels.yaml
- transformer-suffixprefix.yaml
images:
  - name: redmine-create-ticket-webhook
    newName: abeyuki/redmine-create-ticket-webhook
    newTag: "1.0.0"
replicas:
- name: redmine-create-ticket-webhook
  count: 1
