apiVersion: v1
kind: Secret
metadata:
  name: avp-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/webhook/redmine-create-ticket-webhook"
stringData:
  REDMINE_URL: <REDMINE_URL>
  REDMINE_API_KEY: <REDMINE_API_KEY>
  REDMINE_PROJECT_ID: <REDMINE_PROJECT_ID>
  RDMINE_TRACKER_ID: <RDMINE_TRACKER_ID>
