apiVersion: v1
kind: Service
metadata:
  name: redmine-create-ticket-webhook
spec:
  selector:
    app.kubernetes.io/name: redmine-create-ticket-webhook
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-create-ticket-webhook
  labels:
    app.kubernetes.io/name: redmine-create-ticket-webhook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redmine-create-ticket-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redmine-create-ticket-webhook
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                -  redmine-create-ticket-webhook
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redmine-create-ticket-webhook
        image: redmine-create-ticket-webhook
        imagePullPolicy: Always
        env:
        - name: REDMINE_URL
          valueFrom:
            secretKeyRef:
              name: avp-secret
              key: REDMINE_URL
        - name: REDMINE_API_KEY
          valueFrom:
            secretKeyRef:
              name: avp-secret
              key: REDMINE_API_KEY
        - name: REDMINE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: avp-secret
              key: REDMINE_PROJECT_ID
        - name: RDMINE_TRACKER_ID
          valueFrom:
            secretKeyRef:
              name: avp-secret
              key: RDMINE_TRACKER_ID
        - name: TZ
          value: "Asia/Tokyo"
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 125Mi
            cpu: "0.25"
        ports:
        - containerPort: 5000
